# Generated by Django 4.2.26 on 2025-11-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=16)),
                ('stock_name', models.CharField(blank=True, max_length=500, null=True)),
                ('stock_exchange', models.CharField(blank=True, max_length=10, null=True)),
                ('stock_group', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('stock_symbol', 'stock_exchange')},
            },
        ),
        migrations.CreateModel(
            name='Candlestick',
            fields=[
                ('candle_id', models.AutoField(primary_key=True, serialize=False)),
                ('candle_date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('prev_close_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('number_of_trades', models.BigIntegerField(blank=True, null=True)),
                ('number_of_shares', models.BigIntegerField(blank=True, null=True)),
                ('net_turnover', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('stock', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, to='csv_upload.stock')),
            ],
            options={
                'db_table': 'candlesticks',
                'unique_together': {('stock', 'candle_date')},
            },
        ),
    ]
