# Generated by Django 4.2.26 on 2025-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_upload', '0002_stock_candlestick'),
    ]

    operations = [
        # Remove the file field and add new fields for metadata-only storage
        migrations.RemoveField(
            model_name='csvfile',
            name='file',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='filename',
            field=models.CharField(default='unknown.csv', help_text='Original filename of the uploaded CSV', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='exchange',
            field=models.CharField(default='BSE', help_text='Exchange name extracted from filename', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvfile',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded and processed', null=True),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='stocks_processed',
            field=models.IntegerField(default=0, help_text='Number of stocks processed from this file'),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='candlesticks_processed',
            field=models.IntegerField(default=0, help_text='Number of candlestick records processed from this file'),
        ),
        migrations.AlterModelOptions(
            name='csvfile',
            options={'ordering': ['-upload_timestamp']},
        ),
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together={('filename', 'upload_timestamp')},
        ),
    ]
